### ISSUE TITLE
add analytics!

### ISSUE THREAD

**Issue by mmckegg** [mmckegg/loopjs-www#2]
@ahdinosaur were you telling me about a good open source analytics tool the other day, or did I imagine it?

**Comment by ahdinosaur** [comment]
yup, [piwik](https://github.com/piwik/piwik).

**Comment by mmckegg** [comment]
done this, like ages ago: https://github.com/mmckegg/loopjs-www/commit/b33854669e629a79a0c137eb5ba48bc6e568e80c
